### ISSUE TITLE
Document support for RRULES and X-

### ISSUE THREAD

**Issue by j0hnwhyte** [apognu/gocal#2]
Hi
It seems that the project actually supports RRULES and custom attributes, it should be appropriate to put this information in the README (which is wrong if what I'm saying is true). Also it could be nice to have some bare details on how the repetition parsing works and how to get custom attributes.

Thanks

**Comment by apognu** [comment]
I just updated the README (which was indeed outdated) with some information on recurring rules and custom attributes, as well as added examples for those two use cases in the ```examples/``` directory.

Also added information on how to define the date range for the parsing (next 3 months by default).

Do not hesitate to tell me if something feels missing.

**Comment by j0hnwhyte** [comment]
Thank you, I'm trying to implement this library in my code right now, I'll let you know if I can find any verifiable problem.

**Comment by apognu** [comment]
Do not hesitate to open an issue if you find something missing or if some parsing is buggy.
