### ISSUE TITLE
Request for permissions to add branch, so that I can raise a pull request

### ISSUE THREAD

**Issue by GideonPotok** [apognu/gocal#24]
Hi,

I have local branch with a small fix. I would like to push the branch to origin and then raise a PR. Please provide my user account permissions so I can proceed with my contribution. 

<img width="764" alt="image" src="https://user-images.githubusercontent.com/31429832/170826675-2523f495-8e86-4450-aac1-976d8f0ec770.png">
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/31429832/170826713-0dd5ef2a-ceb0-4639-bc48-645acccab700.png">
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/31429832/170826726-d72c47b2-fe8e-4789-b238-770e6457b8f6.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/31429832/170826820-3f59f58c-893c-4133-a905-79c16b7514c6.png">

**Comment by apognu** [comment]
This is not how pull requests work.

You should fork the repository on your own account, push your branch there and create a pull request from your fork's branch to upstream.
