### ISSUE TITLE
Accept any date range

### ISSUE THREAD

**Issue by j0hnwhyte** [apognu/gocal#4]
Another issue I'm trying to solve, the parser actually wants the date of the event before parsing the event. This is problematic as I want to load an event without knowing which date range it's in. An ugly solution would be to use a very large date range, but... well

I'm questioning the need for this parameter as mandatory. My best guess is that it's in place to prevent recurring events to become infinite, but by looking at these lines it seems not:
```go
if gc.buffer.IsRecurring {
  rInstances = append(rInstances, gc.ExpandRecurringEvent(gc.buffer)...)
} else {
  if gc.buffer.End == nil || gc.buffer.Start == nil {
    continue
  }
  if gc.buffer.End.Before(*gc.Start) || gc.buffer.Start.After(*gc.End) {
    continue
  }

  gc.Events = append(gc.Events, *gc.buffer)
}
```

Before going ahead and adding a way to avoid this check in the code, I wanted to discuss this thing with you, so the library remains coherent. Are there any hazards in removing this condition (therefore making it optional)?

Thanks

**Comment by apognu** [comment]
As far as I can remember, ```ExpandRecurringEvent``` does check when it crosses the ```End``` date (with ```Gocal.IsInRange``` for example), so expansion can stop.

Without limits, expansion never stops and memory usage skyrockets until OOMkiller kicks in.

My recommendation would be to call Gocal in batch, period of time by period of time, until you find what you are looking for (which is, I believe, what any calendaring application does under the hood).

What application did you have in mind?

**Comment by j0hnwhyte** [comment]
I ran some experiments, I can confirm that the repetition runs until the end date is reached. Maybe a good approach would be to put the limitation for recurring events but not for the event itself, so an event in any date is matched, and a recurring event "expands" only in the given time range.

My application creates statistics from events in my calendar, which are quite accurate through the day. The module I'm developing now is the reader that loads the data in the DB

**Comment by apognu** [comment]
Sorry about the delay, I didn't get the time to fix this before. I don't know if this is still an issue for you, but the latest commit on master should do it. Could you see if it is OK for you?

This is still opt-in, so as not to break existing implementation, but you can set `SkipBounds` to `true` on your `Gocal` struct.

**Comment by j0hnwhyte** [comment]
Due to external conditions I changed approach in my software, so I don't have the necessity to check this anymore. Thanks for your interest though.

**Comment by apognu** [comment]
Alright, closing this then.
