### ISSUE TITLE
Problem with timezones from outlook ical files

### ISSUE THREAD

**Issue by mogensen** [apognu/gocal#8]
When getting a ical file from outlook I get the following start and end time:

```
DTSTART;TZID=Romance Standard Time:20190513T093000
DTEND;TZID=Romance Standard Time:20190513T094500
```
As outlook has deiceded to use windows timezones instead of standard timezones, this does not work as expected.

I would expect something like the following to parse:

```golang
func Test_ParseTimeTZID_RomanceStandardTime(t *testing.T) {
	ti, err := ParseTime("20150910T135212", map[string]string{"TZID": "Romance Standard Time"}, TimeStart)
	tz, _ := time.LoadLocation("Europe/Paris")

	assert.Equal(t, nil, err)

	assert.Equal(t, 10, ti.Day())
	assert.Equal(t, time.September, ti.Month())
	assert.Equal(t, 2015, ti.Year())
	assert.Equal(t, 13, ti.Hour())
	assert.Equal(t, 52, ti.Minute())
	assert.Equal(t, 12, ti.Second())
	assert.Equal(t, tz, ti.Location())
}
```

Is it possible to extend the implementation of the timezone handling to work with outlook ical files?

**Comment by apognu** [comment]
Instead of trying and parse all possible timezone representation, I added a way to provide one's own mapping for timezone names.

You can refer to the README or the example

**Comment by apognu** [comment]
Instead of trying and parse all possible timezone representation, I added a way to provide one's own mapping for timezone names.

You can refer to the README for usage information.

**Comment by mogensen** [comment]
Very nice! Thank you for the quick fix! :+1:
